---
title: "Results"
---

```{r getting set up, echo = FALSE}
options(repos = list(CRAN="http://cran.rstudio.com/"))

library(tidyverse)
library(readxl)

file_path <- './20221208.xlsx'
data <- read_excel(path = file_path)
```

### **Exploring the Data**

Here's a quick look at the read-in data's first 20 columns, including their label, class, and some data points.

```{r data first look}
data %>% # Using read-in data
  .[,1:20] %>% # Subset the first 20 columns
  dplyr::glimpse() # Using the glimpse() function in dplyr
```

```{r configure ordinal data, echo = FALSE}
# new data frame where StateResidence is categorical and MangMarshFishAccess is ordinal
data_fac <- data
data_fac$StateResidence <- as.factor(data_fac$StateResidence) 

data_fac <- data_fac %>%
  mutate(StateResidence = recode(StateResidence, '1' = 'Florida', '2' = 'Texas')) %>%
  mutate(MangMarshFishAccess = recode(MangMarshFishAccess, 
                                      '1' = "Mangroves are Much Better",
                                      '2' = "Mangroves are Slightly Better",
                                      '3' = "No Difference",
                                      '4' = "Marshes are Slightly Better",
                                      '5' = "Marshes are Much Better",
                                      '6' = "I don't know")) %>%
  mutate(MangMarshFisheries = recode(MangMarshFisheries, 
                                      '1' = "Mangroves are Much Better",
                                      '2' = "Mangroves are Slightly Better",
                                      '3' = "No Difference",
                                      '4' = "Marshes are Slightly Better",
                                      '5' = "Marshes are Much Better",
                                      '6' = "I don't know")) 


data_fac$MangMarshFishAccess <- factor(data_fac$MangMarshFishAccess, levels = c("Mangroves are Much Better", 
                                                       "Mangroves are Slightly Better",
                                                       "No Difference",
                                                       "Marshes are Slightly Better",
                                                       "Marshes are Much Better",
                                                       "I don't know", ordered = TRUE))

data_fac$MangMarshFisheries <- factor(data_fac$MangMarshFisheries, levels = c("Mangroves are Much Better", 
                                                       "Mangroves are Slightly Better",
                                                       "No Difference",
                                                       "Marshes are Slightly Better",
                                                       "Marshes are Much Better",
                                                       "I don't know", ordered = TRUE))
```

How many respondents are from each state?

```{r StateResidence viz, echo = FALSE}
data_fac %>% 
  drop_na(StateResidence) %>%
  ggplot() + geom_bar(aes(y = StateResidence))
```

### **Data Viz and Stats**

# **Providing Access to Fishing Areas v. State of Residence**

```{r MangMarshFishAccess v. StateResidence plot, echo = FALSE}
install.packages("viridis")
library(viridis)

data_fac %>%
  drop_na(StateResidence) %>% # remove NA from state responses
  drop_na(MangMarshFishAccess) %>% # remove NA from response variable
  filter(MangMarshFishAccess != "I don't know") %>% # remove "I don't know" from response variable
  ggplot(aes(fill = MangMarshFishAccess, x = StateResidence)) + # plot fishing access across states
  geom_bar(position = "fill") + # stacked bar chart
  ggtitle("Perceptions of Fishing Access by State") +
  xlab("State of Residence") + ylab("Proportion of Respondents") +
  guides(fill=guide_legend(title=NULL)) + #removes legend title
  scale_y_continuous(labels=scales::percent) + # scales y-axis to 100%
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_viridis(discrete = TRUE)
```

Statistically significant? **Yes**.

```{r  MangMarshFishAccess v. StateResidence stat}
data1 <- data %>%
  filter(MangMarshFishAccess != 6) %>% # remove "I don't know" responses
  filter(MangMarshFisheries != 6)

wilcox.test(MangMarshFishAccess ~ StateResidence, data = data1, na.rm = TRUE)
```
# **Supporting Coastal Fisheries v. State of Residence**

```{r MangMarshFisheries v. StateResidence plot, echo = FALSE}
data_fac %>%
  drop_na(StateResidence) %>% # remove NA from state responses
  drop_na(MangMarshFisheries) %>% # remove NA from response variable
  filter(MangMarshFisheries != "I don't know") %>% # remove "I don't know" from response variable
  ggplot(aes(fill = MangMarshFisheries, x = StateResidence)) + # plot fishing access across states
  geom_bar(position = "fill") + # stacked bar chart
  ggtitle("Perceptions of Fisheries Support by State") +
  xlab("State of Residence") + ylab("Proportion of Respondents") +
  guides(fill=guide_legend(title=NULL)) + #removes legend title
  scale_y_continuous(labels=scales::percent) + # scales y-axis to 100%
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_viridis(discrete = TRUE)
```
```{r MangMarshFisheries v. StateResidence stat}
wilcox.test(MangMarshFisheries ~ StateResidence, data = data1, na.rm = TRUE)
```
Statistically significant? **Yes**.